nr12

diff --git a/.github/workflows/my_first_actions.yaml b/.github/workflows/my_first_actions.yaml
--- a/.github/workflows/my_first_actions.yaml
+++ b/.github/workflows/my_first_actions.yaml
@@ -11,29 +11,30 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-latest, windows-latest, macos-latest]
-        python-version: ["3.8", "3.9", "3.10", "3.11"]
+        python-version: [3.8, 3.9, 3.10, 3.11]
     runs-on: ${{ matrix.os }}
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Set up Python
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
 
-    - name: Lint with Ruff
-      run: |
-        pip install ruff
-        ruff src || echo "Linting issues detected."
+      - name: Lint with Ruff
+        run: |
+          pip install ruff
+          ruff src || echo "Linting issues detected."
 
-    - name: Test with pytest
-      run: |
-        pip install pytest
-        pytest src || echo "Some tests failed."
+      - name: Test with pytest
+        run: |
+          pip install pytest
+          pytest src || echo "Some tests failed."
+
